# Generated by Django 3.1.1 on 2020-09-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_persondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('order_date', models.DateField()),
                ('ship_date', models.DateField()),
                ('deliver_date', models.DateField()),
                ('coo', models.CharField(max_length=100)),
                ('cod', models.CharField(max_length=100)),
                ('seller_id', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_time', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='category',
            field=models.CharField(default='electronics', max_length=100),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='item_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='sellers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='sellers_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
