# Generated by Django 3.1.1 on 2020-09-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200919_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('seller_id', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='Items',
        ),
    ]
