# Generated by Django 3.1.1 on 2020-09-26 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_auto_20200924_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondetails',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='persondetails',
            name='pid',
        ),
        migrations.AddField(
            model_name='persondetails',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
