# Generated by Django 3.1.2 on 2020-11-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=0.000135013501350135),
            preserve_default=False,
        ),
    ]
